### ISSUE TITLE
the link under prerequisites under https://scully-image.github.io/docs/getting-started is broken

### ISSUE THREAD

**Issue by Dan0xE** [cmgriffing/scully-image#46]
The site where its linking to returns "SORRY, COULD NOT LOAD STATIC PAGE CONTENT" and a bunch of 404
the link can be found here

![image](https://user-images.githubusercontent.com/23116945/185513787-e1fe9594-1888-4cb6-97d1-6a4528ee9443.png)

the link "https://scully.io/docs/getting-started" is refering to the wrong site(?) is my guess

what is getting returned: 

![image](https://user-images.githubusercontent.com/23116945/185513956-b459b66d-6166-4d44-a67c-85a5e55acdc2.png)

![image](https://user-images.githubusercontent.com/23116945/185514004-09dc8e51-85c2-46a8-9d56-43ce518a79bc.png)

**Comment by cmgriffing** [comment]
Good call. Looks like the correct link is now: https://scully.io/docs/learn/getting-started/overview/
